[package]
name = "worth"
version = "0.0.1"
publish = false
description = "A balance tracking desktop app"
authors = [ "Callum Watkins <callum@callumwatkins.com>" ]
license = "AGPL-3.0-only"
edition = "2021"

[lib]
name = "worth_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tauri = { version = "2.9.4", features = [] }
